"""
Geometry Visualizer

Combines OpenMC-generated XY and XZ plots with a color legend.
Colors come directly from OpenMC - not hardcoded.
"""

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.image as mpimg
from pathlib import Path


def create_geometry_plot(
    xy_plot_path: Path,
    xz_plot_path: Path,
    output_path: Path,
    color_legend: dict,
):
    """
    Combine OpenMC XY and XZ plots with material color legend.

    Args:
        xy_plot_path: Path to OpenMC XY slice PNG
        xz_plot_path: Path to OpenMC XZ slice PNG
        output_path: Where to save combined plot
        color_legend: dict from OpenMC {material_name: (R, G, B)}
    """

    # Load OpenMC plots
    img_xy = mpimg.imread(str(xy_plot_path))
    img_xz = mpimg.imread(str(xz_plot_path))

    fig = plt.figure(figsize=(14, 8))

    # Layout: XY (left), XZ (center), legend (right)
    ax_xy = fig.add_axes([0.02, 0.1, 0.35, 0.8])
    ax_xz = fig.add_axes([0.40, 0.1, 0.35, 0.8])
    ax_legend = fig.add_axes([0.78, 0.1, 0.20, 0.8])

    # XY plot
    ax_xy.imshow(img_xy)
    ax_xy.set_title('XY Cross-Section (top-down)', fontsize=12, fontweight='bold')
    ax_xy.axis('off')

    # XZ plot
    ax_xz.imshow(img_xz)
    ax_xz.set_title('XZ Cross-Section (side view)', fontsize=12, fontweight='bold')
    ax_xz.axis('off')

    # Legend - colors from OpenMC
    ax_legend.axis('off')
    ax_legend.set_xlim(0, 1)
    ax_legend.set_ylim(0, 1)

    ax_legend.text(0.1, 0.95, 'MATERIALS', fontsize=14, fontweight='bold',
                   family='monospace', transform=ax_legend.transAxes)
    ax_legend.text(0.1, 0.90, '(from OpenMC)', fontsize=9, style='italic',
                   alpha=0.7, transform=ax_legend.transAxes)

    y = 0.82
    for mat_name, rgb in color_legend.items():
        # Convert RGB (0-255) to matplotlib format (0-1)
        color = (rgb[0]/255, rgb[1]/255, rgb[2]/255)

        # Draw color swatch
        rect = mpatches.FancyBboxPatch(
            (0.1, y - 0.02), 0.15, 0.06,
            boxstyle="round,pad=0.01",
            facecolor=color,
            edgecolor='black',
            linewidth=1,
            transform=ax_legend.transAxes
        )
        ax_legend.add_patch(rect)

        # Material name
        ax_legend.text(0.30, y, mat_name, fontsize=12, family='monospace',
                       verticalalignment='center', transform=ax_legend.transAxes)
        y -= 0.10

    # Footer
    fig.text(0.5, 0.02, 'Geometry plots generated by OpenMC',
             ha='center', fontsize=9, style='italic', alpha=0.6)

    plt.savefig(output_path, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close()

    return output_path
