"""
Core utilities for crit-buddy.

Provides configuration loading and shared material definitions.
"""

from .config import ExperimentConfig, Case, generate_cases, expand_sweeps
from .material_conversions import (
    AVOGADRO,
    ATOMS_PER_BARN_CM_TO_ATOMS_PER_CM3,
    ATOMS_PER_CM3_TO_ATOMS_PER_BARN_CM,
    MaterialNuclideSummary,
    MaterialSummary,
    atom_densities_to_atom_fractions,
    atom_densities_to_mass_densities,
    atom_densities_to_weight_fractions,
    atom_fractions_to_atom_densities,
    atom_to_weight_fractions,
    average_atomic_mass,
    get_atomic_masses,
    normalize_fractions,
    summarize_openmc_material,
    weight_fractions_to_atom_densities,
    weight_to_atom_fractions,
)
from .template import ProblemTemplate, ParameterSpec
from .template_loader import (
    load_model_class,
    load_model_module,
    load_template_class,
    load_template_module,
)
from .materials import (
    aluminum,
    air_dry,
    concrete_ordinary,
    create_uf6,
    create_fissile_material,
    create_environment_material,
    get_material,
    get_density,
    humid_air,
    MATERIAL_LIBRARY,
    MATERIAL_DENSITIES,
    MATERIAL_REGISTRY,
    stainless_steel_304,
    stainless_steel_316,
    uo2f2,
    vacuum,
    void,
    water,
)

__all__ = [
    "ExperimentConfig",
    "Case",
    "generate_cases",
    "expand_sweeps",
    "AVOGADRO",
    "ATOMS_PER_BARN_CM_TO_ATOMS_PER_CM3",
    "ATOMS_PER_CM3_TO_ATOMS_PER_BARN_CM",
    "MaterialNuclideSummary",
    "MaterialSummary",
    "ProblemTemplate",
    "ParameterSpec",
    "atom_densities_to_atom_fractions",
    "atom_densities_to_mass_densities",
    "atom_densities_to_weight_fractions",
    "atom_fractions_to_atom_densities",
    "atom_to_weight_fractions",
    "average_atomic_mass",
    "get_atomic_masses",
    "load_model_class",
    "load_model_module",
    "load_template_class",
    "load_template_module",
    "normalize_fractions",
    "aluminum",
    "air_dry",
    "concrete_ordinary",
    "create_uf6",
    "create_fissile_material",
    "create_environment_material",
    "get_material",
    "get_density",
    "humid_air",
    "MATERIAL_LIBRARY",
    "MATERIAL_DENSITIES",
    "MATERIAL_REGISTRY",
    "stainless_steel_304",
    "stainless_steel_316",
    "summarize_openmc_material",
    "uo2f2",
    "vacuum",
    "void",
    "water",
    "weight_fractions_to_atom_densities",
    "weight_to_atom_fractions",
]
